import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/global/Nav";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const user = await auth()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav user={user} />
        {children}
      </body>
    </html>
  );
}
